site_name: "ipfs-kvs"
repo_url: https://github.com/nanoswap/ipfs-kvs
edit_uri: blob/main/docs/
site_url: https://nanoswap.github.io/ipfs-kvs

nav:
  - Home: 'index.md'
  - Classes:
      - 'Ipfs': 'classes_ipfs.md'
      - 'Store': 'classes_store.md'
      - 'Index': 'classes_index.md'
  - About:
      - 'License': 'LICENSE.md'

theme:
  name: "readthedocs"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]  # search packages in the src folder
