site_name: "ipfskvs"
repo_url: https://github.com/nanoswap/ipfskvs
edit_uri: blob/main/docs/

nav:
  - Home: 'index.md'
  - Classes:
      - 'Ipfs': 'classes_ipfs.md'
      - 'Store': 'classes_store.md'
      - 'Index': 'classes_index.md'
  - About:
      - 'License': 'LICENSE.md'

theme:
  name: "readthedocs"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [.]  # actually not needed, default

extra:
    version: 0.0.4
