name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r requirements-dev.txt
      - run: mkdocs build
      - run: mkdocs gh-deploy --clean --config-file mkdocs.yml --force
