name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdocs gh-deploy --config-file mkdocs.yml --force
